#!/bin/bash

# Useful for quick cleanup at development process

php artisan cache:clear
php artisan route:clear
php artisan view:clear
php artisan config:clear
php artisan config:cache

php artisan migrate:refresh --seed
