services:
  php:
    container_name: laravel_php
    image: laravel-demo-php
    build: 
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        UID: "${USER_ID}"
    user:
      "${USER_ID}:${USER_ID}"
    volumes:
      - ./.docker/php/php-development.ini:/usr/local/etc/php/php.ini
      - application:/var/www/html:rw
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    container_name: laravel_db
    image: postgres:alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # env_file:
    #   - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: laravel_redis
    image: redis:alpine
    networks:
      - app-network

  nginx:
    container_name: laravel_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - application:/var/www/html:ro
    depends_on:
      - php
      - postgres
      - redis
    networks:
      - app-network

volumes:
  postgres_data:
  application:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}"

networks:
  app-network:
    driver: bridge
